DROP TABLE IF EXISTS BUDDIES;
CREATE TABLE BUDDIES (
    ID UUID PRIMARY KEY
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    ID UUID PRIMARY KEY,
    USER_NAME VARCHAR,
    USER_EMAIL VARCHAR,
    BUDDIES_ID UUID,
    FOREIGN KEY (BUDDIES_ID) REFERENCES BUDDIES(ID)
);
