INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED) VALUES (1, 'Pink Elephant', 'pink.elephant@gmail.com', false);
INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED) VALUES (2, 'Green Dinosaur', 'green.dinosaur@gmail.com', false);
INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED) VALUES (3, 'Hiruna Smith', 'hiruna.smith@gmail.com', false);

INSERT INTO BUDDIES (ID, USER_0_ID, USER_1_ID) VALUES (1, 1, 2);
INSERT INTO BUDDIES (ID, USER_0_ID, USER_1_ID) VALUES (2, 1, 3);

INSERT INTO MESSAGES (ID, SENDER_ID, RECEIVER_ID, TIMESTAMP, CONTENT, IS_READ) VALUES (1, 1, 2, '2022-03-16 14:29:36', 'HARRO', true);
INSERT INTO MESSAGES (ID, SENDER_ID, RECEIVER_ID, TIMESTAMP, CONTENT, IS_READ) VALUES (2, 2, 1, '2022-03-16 14:40:21', 'Yo HARRO', false);
