INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED) VALUES (1, 'Pink Elephant', 'pink.elephant@gmail.com', false);
INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED)  VALUES (2, 'Green Dinosaur', 'green.dinosaur@gmail.com', false);

INSERT INTO COURSE (COURSE_ID, COURSE_NAME, SEMESTER, STUDENT_COUNT, TIME_UPDATED) VALUES
    (1, 'SOFTENG 701', 'Semester 1 2022', 10, '2022-03-16 14:29:36');

INSERT INTO COURSE_STUDENT (COURSE_ID, USER_ID) VALUES
    (1, 1);
INSERT INTO COURSE_STUDENT (COURSE_ID, USER_ID) VALUES
    (1, 2);
