INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED) VALUES (1, 'Pink Elephant', 'pink.elephant@gmail.com', false);
INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED) VALUES (2, 'Green Dinosaur', 'green.dinosaur@gmail.com', false);
INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED) VALUES (3, 'Hiruna Smith', 'hiruna.smith@gmail.com', false);
INSERT INTO USER (ID, USER_NAME, USER_EMAIL, USER_PAIRING_ENABLED) VALUES (4, 'Flynn Smith', 'flynn.smith@gmail.com', false);

INSERT INTO COURSE (COURSE_ID, COURSE_NAME, SEMESTER, STUDENT_COUNT, TIME_UPDATED) VALUES
    (1, 'SOFTENG 701', 'Semester 1 2022', 3, '2022-03-16 14:29:36');

INSERT INTO COURSE_STUDENT (COURSE_ID, USER_ID) VALUES
    (1, 1);
INSERT INTO COURSE_STUDENT (COURSE_ID, USER_ID) VALUES
    (1, 2);
INSERT INTO COURSE_STUDENT (COURSE_ID, USER_ID) VALUES
    (1, 4);

INSERT INTO BUDDIES (ID, USER_0_ID, USER_1_ID) VALUES (1, 1, 2);
INSERT INTO BUDDIES (ID, USER_0_ID, USER_1_ID) VALUES (2, 1, 3);
INSERT INTO BUDDIES (ID, USER_0_ID, USER_1_ID) VALUES (3, 1, 4);

INSERT INTO BUDDIES (ID, USER_0_ID, USER_1_ID) VALUES (4, 2, 3);
INSERT INTO BUDDIES (ID, USER_0_ID, USER_1_ID) VALUES (5, 2, 4);
